apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 15.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: postgres-ha-secret
    primary:
      persistence:
        enabled: true
        storageClass: local-path
        size: 20Gi
