apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: data-storage
spec:
  interval: 15m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # InfluxDB 2.x configuration
    image:
      repository: influxdb
      tag: "2.7-alpine"
      pullPolicy: IfNotPresent

    # Admin user configuration
    adminUser:
      organization: "home-automation"
      bucket: "home-assistant"
      user: "admin"
      # Retention: 0s = infinite (multi-year retention for energy/climate data)
      # Data will be retained as long as storage allows
      retention_policy: "0s"
      # Credentials from sealed secret
      existingSecret: "influxdb-admin"

    # Persistence configuration
    persistence:
      enabled: true
      storageClass: "nfs-storage"
      size: 20Gi
      accessMode: ReadWriteOnce

    # Node selector to run on pi-lab (where NFS is mounted)
    nodeSelector:
      kubernetes.io/hostname: pi-lab

    # Service configuration
    service:
      type: ClusterIP
      port: 8086
      targetPort: 8086

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # InfluxDB engine configuration
    # Optimized for Raspberry Pi with long-term storage
    env:
      - name: INFLUXD_STORAGE_SHARD_PRECREATOR_CHECK_INTERVAL
        value: "10m"
      - name: INFLUXD_STORAGE_SHARD_PRECREATOR_ADVANCE_PERIOD
        value: "30m"
      # Shard group duration: 7 days
      # Balances query performance with file count on NFS
      # Longer duration = fewer files, better for Pi/NFS
      # Shorter duration = more granular data management
      - name: INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE
        value: "256m"
      - name: INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE
        value: "64m"
      - name: INFLUXD_STORAGE_CACHE_SNAPSHOT_WRITE_COLD_DURATION
        value: "10m"
      - name: INFLUXD_STORAGE_COMPACT_FULL_WRITE_COLD_DURATION
        value: "4h"
      - name: INFLUXD_STORAGE_COMPACT_THROUGHPUT_BURST
        value: "48m"
      - name: INFLUXD_STORAGE_MAX_CONCURRENT_COMPACTIONS
        value: "2"
      - name: INFLUXD_STORAGE_MAX_INDEX_LOG_FILE_SIZE
        value: "1m"
      - name: INFLUXD_STORAGE_SERIES_ID_SET_CACHE_SIZE
        value: "100"

    # Security context
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    # Health checks
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    # Enable backup (optional)
    backup:
      enabled: false

    # Metrics (for Prometheus)
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false  # Will enable later with monitoring stack
