apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-influxdb2
  namespace: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 20Gi
