---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-admin
  namespace: data-storage
spec:
  encryptedData:
    admin-password: AgBqbAJBJNgwpimjkTYTQn2CAqbp/6/Ur8nRVXy3cNVD26cjQaipFbD+IZAzGaINp1yUiFnkJwzIq5dXg0T6qc/j3Tq0ji29Ra06rA4MqYG4Ct6PyyzP7z2y8uCB/zwqipfXzVFbO54ILcgWcagjZ/nqgp7jxwH8KiE2mdVkIUcgGk8P/S+RMICCCG7Y/zQNYLOFZd8USEjkaGMx+Fc2JBP9+RoJoAYgHSCkQo9xY85Y7UnviYOGHcma/o0k7dsdR3+ezqGXK8YXpGiHXaGxIHz/TZqjOG6phf4o7zWxNrA9l5ZDfkK3VP85FCPEcS0+OAJY5xm658Oanld5SLqycoc2uaynM22kRdtLcZmfSrxScnuWi48EaIjEV5z3i2tBK8kT6kVmzJ9Z8TkMAt6jIdGKI7AOT4QMFyWmgVQIUkUE+OB+pzAR97zEZow6f6Pf2huKXRw0e2gmy5eRunJGYVMLsCACndttxufq54UREZe8OBkOAxiRWVu8vv7AMPdGUzVVBJlPU7XA0HLX72+hYShSocH3vkYloOCd3dG6+Fvg/gUOiSXFiPlr4l+LqtGHUQbNaDVtblGPad9vcG4kp9O49Bho7JK0obk03ZpQ9GZaMC6BopktFYrOTSTavvghUutUL4hjZTSytqEAqW3S4VdFm6/Ysj7pZB295Ad1oLnois/qGKO+j4BpRRa0Uul3t8q56JlLWL0O6IyxaMKw3dI9AopSRd+fYjTSbkxx
    admin-token: AgCKg7w6XHKbWXEo5QmvqZVm6B+EVH+6CG4vsm3gcWVfgrRQ/zKEHHXI/1/skUvHhVpAg5tSWxYvwlNiT8nB4HSMBuS5qKpqdIvXP2LDi/PGBnexekJoTUdtQqYcRv/kTUJVjGc9cpDy7KQMb8Y8rxOUeCZQ+fAvOxmPJC9+aO+Ygorj36UN9Ep9cutcTF2+N/Shr76FFO1zyDJ1XvHa1VJgupYwg3R91jPgHVLDNzQNYEuBHkAGMx2v+J2+rH+fj1oduelqgmEtLXl+GwOoXfh7OmtPhxmWd0H4uZ95hjE8y8XfMBVCRqh4owvn99y51La+TwDvOfGTnFF7uNhGgHJWAKxFXRCfvrgNY32QGGHQojACSJz1GahnoL6qMlfXNBp39oCj0JRwOlyoX/JxUSZlaF/qZgjXTP29Nx5osmsSeIwL1X6svF39u8wyA/x+ncqY1uEzaRutwyv2XhGNC32IjEJVuZAspg+MrnKDkrmdjUbhTenoW/hMIrafdQTHtIEeOrpfXkvOpeIMqjCFUlhcCsKe6MBlTZfkKxGg1OFoysa53ygfnKPvtVwvEYGGxw3qxHMeGZ5paCMobt/cx9BG2URmWmSeEHzXPNUGWyjZFf/msIhUwG7jotyFv90RBYsgUuSgbX0Z/Use8dmrAv29wg3Agy56eUsVxTe1kKjrUUhdKca9cquJtMzelihGY9+SX5RBcCeoj2xD8C6SOtXFibk59895MFpj1yOGUV8Tdg==
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-admin
      namespace: data-storage
