apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
data:
  datasources.yaml: |
    apiVersion: 1
    
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
        editable: true
        
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://influxdb-influxdb2.data-storage.svc.cluster.local:8086
        database: home-assistant
        isDefault: true
        editable: true
        jsonData:
          version: Flux
          organization: home-automation
          defaultBucket: home-assistant
          tlsSkipVerify: true
        secureJsonData:
          token: "INFLUXDB_TOKEN_PLACEHOLDER"
