---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAag4lzKxiPds5aVIMeNQLH+hJoEZQnfPLws58MbY1xeZdjQ3ueNV84CiG+Fv+64FlVfR1uUtEkhESN1Svkz+5FVcebyscaUh1XrHWGbyS0H+/oXjHOHzOLySoZAwgO36G/DWBzmuFm0FfNno0EVqukfQVs6TkiiBfc0jCbDwt1jN20iN1WwghBIovbQ8omT/Oc6C3C+Kc3WM53KfTvFuBUlRbZ7OkK7z5SUxbFn4bTIBtYIhWAV3Q35Hgs0p0bcYuq2aF92DI41qvDHpVoHzJkeaWBgJBUersmiMkUFQASqb7c9/m1fGyFWwL6/cAkVFR1pDfutw7zjC6N8iWmtf+0eHedbF11Q+MvDrnzbvJFxjyovBOVSfkls672KKBfvOEgN688mx5DvXqqoTyCJs2KKaZxWk3SDwxSrUBuIMf9E8HIit3XBO0VUhYCMwmHWJdbhPqDjHiym0zHGVl/UwZvkEvyP8rjqf0YSAlJe+tfCh1h8ylD+OWpR83m0qKCxJS1BzRs/IfmOf4o60h/iN0PVrIoh9x6tr7n9Ut66XC5Cs0KAn7vxTmFRUGUwsMPtMUxXue6lXDOGDWiD7WlLWiRT6/v3klzexKL7/CpEn18Xb+qsPE8K5ocpGbk+ScDaPFs0LujjNUcwaCXP9B8lwUv4Njsgs5jxA3PgcWlN0o8h0IYsbmEPiS0nz1wfRGS8qluhYlruvhN6J+heUdImUM6
    admin-user: AgAlo/gaiaM2J2qa6QwMkWGYU/XOfv/JumAWxBYE5u6eFvb+b6De/R6dSizoDrFsBEFZ3hot46KGLqHXTWAzxItmSe17gB/ArdWFiMwje3/B1BSCiUfNVAqm6dhkF6/lrk+GiYaVKXUjLJIPTpiIb+FCxmfHLhXAA3BECaIsD0z3gOX5Au9USuGFK0opmujVcWk3+ES2Pwr9/gb8L60Z0M13BOnCP5TXD/W16YtrAnJ7Gz0gpiqnZU8MFSWaJMjQzQI/mxOOM4HDiXWDOAQl39b9SBpdc5vMedo/HmpqCD8kJ8ExzgGxmEblPy+B7wMLQn4VKq9KqNa/pIZvriS6WK8fKaE+XxySZHzBgkVu7nBszB3kV13NUR02nfYR5Qeif1EPBH6n/VTBNhm75xAAgOpZYKMBw9zza8QCEdkhpWx7+JdzEeT6Nr/nYXfgEpy7y2WM7jCjSbQ9ovNvVtDDyFtw26NyAskT8elg80yaHIWvBcAS3r9oAyyJRYO2eZIoY7u2NQBhNd59cvBeDg1WmLRG17+zf4+sK/52XEDxXr/0Xt29iHhUlkig5tJtHieRHOGyHcPrRTfIpSC4xI+PzSRg9rT+8LCM0DRu4lDPcA7d/LI9buin6V3xDbVtCx3UlxKwRzyxaKhns/XlTu6PffQk3Bvv1yzWigF5w5h001MiM65E+PkEqgiV8HLIXUQz2qffsb0aAQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: observability
