---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAUwOejKkyNoeX96GUJYDr4FLKuHRdHLTH/gsRgVo2Qt2Dr+Noqgfl9e3qkfVJ5iezjSQ89hUQAxTIkkKBQrmH25mDYR/fssc6pWVN4PHcmAjn1vARf5Fj8sIz3j9LMt+xVE/rB2vXsYEVnTAnngovxmlCTBNiIkfVLaLildpLKGj7r+S4Fgkqj8tZ/Ja6JmzFD13UfMf/X/6w1vOoUbGH1m/OdcHtWq2n3qdmwBYzhYTKlXFXSAZSOA/lkot45lF533KZECVF+4Ie1iLxIN68YytseMStHXzGQB8ba+ekdATsN2SOBKuFtzhLbkAmp9pMwsANISlkMrCfesFodnm5ut7rpQnSR1HfgaFcxbKBxyfqPBJ5l6LcFxp5aao2fxPTQS0SBY3kLjY3ahqOs6/2Re5yrNKfnLePe6EdxkvQG3SyCG+511vHPg/zn+A1eHoVOLcoIqaj2oK0ZJT20TYgBcZ/eZscE5Zm5DhB3+KIwB44wOYZzMNmoQoKaANRFWImTmWy5uuuvGz2nE4dhHUurOu62cFfkn7a6sP+tMRJutwkCZOAu/ZzDNuXfAVfHY81LukJPQZngsjimJaa1jh55pg1Puj2R+ULMAdMhf3I+XGX7ly1SfnBQZY1ChWuqOg7qt2j3TWQkkIuYa0i1zHX2ShxOmzEGkVXffTzQutp1FI8w8h9BFpeZmGJp1tgMcXMqfia+6xxaXg==
    admin-user: AgAWrjHWW//nbWDi8RoY+1TOYGgD08GCyXtx3xUQaJjfxGFg0OhLTrG6hQvfUU2jE1ZRyetG7qvLrMbScDKOf5/xiK/A0fBOXfYE+f3IKAKnt5cw6BCSuasHUgNp3TQTS8DWt/g8r1Y0BrhjeggNfsmXWikb4TBlYyddJIc8JnsRkIH7kMRuM7PL0zpBEuKByUbGaE3Dzneup5EIn9AX+ozqyQ+p37pMr2t9WokNl6AeKfeL7IpndBCDYfMAeW1NDGRis6QIbWMf9fNWaM6V1R2+H4aU/O6CRFZGH68XkKuEBzb/RuxFz9e2z8OCs77PtIU17s6A7ZgQ3fN0sHwQvPCJNHAcA1wikLLxOiOICveVEt539MiV2V4C6mKHhvV2sNTTB5YKyMa8eIs6fU258Ditra7TmCvjaXKnPrsVMyAkuCOPfyquL5VDjzIQy2a0KCL/ByZi5BxZTK64yxD2DqbwqpsqwUi56yVoXzPvbyYo/pWO2VoCUCiBeKVTxNPhlqUoeR4dCfbAHz6lCb80B0IKFhqaapqSVt/rw5b6+VdW0YHz1iEGQb7wQUEg10rdQ2VJQ/R9CDEu/aUuYXl5V40pPWeMIEXQf4Hj04fKtI00sPF9WXmB3CWxX6fHh1WAHfHs2sBIucLBzC/Z8cOXPcm9N9LT2pyBSue0k7YmwmdEl9E5UOfOeAnYTaN7rHujkv1rn+fvfA==
  template:
    metadata:
      name: grafana-credentials
      namespace: observability
