---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBO2BEtiQZQqJUrqb0Mf+D2Y99+zJGvHnYm/f4BGUkPIleUbUIcNd1eHrivFaC9V3A9mVro4aZKV5xY58CJ09YQTzUUuhQ448BfymS73CwA69AHRaW0GeFxIzsZT1uac3/Dnhllj9HP8G8XABaQuY4AZ2YH47CIumUye112ognzVj8BOnA9AOfwwwgOBioEN5TOJRqK/lHynIxPv57KDtk9s5Ck5d5tEbz4b2KDSTmz1C6wU9iNa8d55unIUf3Y6GBHokAn+SPp3i/+1yw8J5tooFp9HgBm9cqyCS/+2kKGgI/RHSp0VTrIE/9qW00j9F+1D0alV0/jTqh5HrwDPPFD+n9o37xI89mETjc7YFCWbQt1viuaSohp6LKlNqJoQs/IZGvBXI5CCbsWShAMjHbPT+9NTt5wYtGCGWH2+m06n5XktLw4iXZYQAIwvrlYU0PfXI/2h2s3j6ctbUaOakrYyN4F/BPOJN7xoL9sc/yAGdUQ13WaYwvlPpiNTpeAH1idONYgBNBS9MHlRBhrlkAPiMpnZf+4QtDSoYBwtwzDHo4wGmCpD8RV/E2sboOQ4/U3t2ry65RGROzdCZKOA4hjiGB7G64hq3wcpICviVNKA8yO0V6KPW+q6nEyXaoAZTLn+XOddmhgLqAVyirQAnCK+4QjUV2w+Cu5cBGU5gcwtZmuS/VCoGP7gtf7vAHv93uPsiL2oLQziQ==
    admin-user: AgALd+wyLLIuAhdMRdMprJy8AvZwkTiGKMvW/tBMZBlXa1EY3Jo9wmE06jh0kXl9qlPLkTliYOP287oVFrswwjJUfde15t1YWHxbWxStLDyIqP5jAQuc/i7rf4afhmQGidp1if/H5vERWoo/svksJx66ZpyWVmTkVByH9MNpI8FcGAzdrtP455rTPaxHgzmxIzmFnpFt5S+fuTomfepjvbrGmqZXz11qRBIQ0zFxt4r5sYFYEJUcfLBDDRQPb1XDSbRFSzjN2ebNluy+6g7UmTWB0kPbLPFhDzJsuxqiEke2rP408SKyul1rG9cYOqCdD/yQdh9EThKDtpqfk2xR9+9sh2NDphzUDkQOQ648VRMtGR7OyozShWwpJDQOxfuC0EskXOpon6k2qxA24QU1CBqmTJlReI7It6VESLgpr/MV7O3rs0Am8DHuzqvujggB0mCRt4yLhziFfAYkxav/aYLp95tLndk6Y2U0Cys2IlW81vZyfTbYF3s08uk9NvEja2m3JlBaglbcKd+TodHk41D/y8CSoW66PUhNwxaMNtfZ8gtZTM/yU4aYfh++X6apUaeixzNlhWTZmwGXEN25tEha/CjlSX1JDylinPldsqzmk4/WCyLP9LC3JNeNDhpQA9D8Jkyi9mspEEpIQC9fOHUWnDy+NBfYltTPZEkWwuWofzwhMi31gCJXqrAwRZmK/qeC1qwTQw==
  template:
    metadata:
      name: grafana-credentials
      namespace: observability
