apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: observability
spec:
  encryptedData:
    admin-user: REPLACE_WITH_SEALED_SECRET
    admin-password: REPLACE_WITH_SEALED_SECRET
  template:
    metadata:
      name: grafana-credentials
      namespace: observability
    type: Opaque
