---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAOj2MM+0rBUbQ+XF97TXbTdtd5yPjoOGQ4POGHj7sOMsY/AHhySwqB+ZvASBHEsbn2xGJOMVTSwe0GBjlbHVzmhJx+Yd1zxCm2EhKKLLVUp6MXWEVLDFpK5FaA+O4QaPjVsO7iUJnlDAGsef7EhzfIV5E1fAgM89aT5csl5uy2ZOYVhYFZJ8TqEMysyJJpQ9rAW87ZpmE5m+Ex57sgoAmBm9jG32zdD9R0+ck8xWDrYrgzYXEvW2NX4dEryTfCzf2xwNcidnHmWcN0Y3nfQ8yrNjrplHEHvikqYeGXBRbBRPUdsKUzIQjIjiHQvhh9oWmoXWQAXXkCBvgOPO3thKh9D0vZINNb03hC0yyhtwl4HO2S7TqVnXQxxwYAwC6RfGEDSGOqo/LZqCZluB2lq8Rw1pI9rEnmUY40HxDWlymsipMmLVp4xUneTKX0ZzTNh2D1O3Z/FE4599/CNS2rzkHlv3UCRabfObOyVyXTNoHMyMbLepPzrxAWGvK7zsdJ5jcDhtCs81YOaYzLgpkXb4nVNMy1mG+YAPh3MDaEU6sveUagQkgMuqyFVgauGKOuWDA1ZVsTSa9PYYyrZiwP6Zo6R99cJoFU9qBl8WipznbbCcVB6sO8Y1MzwJbl6jZ6CeIEXXoOrAsDe/IfRy2zmYgWMIUd7Oe94RPkbOP1G/8+IFWHU98Yu3NyqsC45ONPB20hRgQ84EB4C1MDwqfxI8dESrXcS0TTEBZY90ZiLGs=
    admin-user: AgBQY/jpK2VeRV2VCMV85TuZMafUkwCnNnRG5i6E7CJkQs+ySl/Gae3ylnyfRazG2M6siwBoKbEpBWXD1TNU3YVm8H3ljhSc2GizPZnohhKU6yneDA28KbrkRll0xUtMwtkB9zN0vdggCRjouXwcPBO0QxWaKB+cI3c+AUrXw9r550dGcICPjYZ9M1Tb56C2eWlVm1Qlph2TFvtL8mQ4bUj2uiAeEMLraDsGQ77vZWi9Bs4KWxqmDOp34h5wK1H9l8f5Wk+WaJs6eM6vMOaoQfw5umF5SuG/Oxnz4mALAysIZYK1ZD1oeWtb2pEQ3dxQJLlp7YLQS3K9kzhm+6JvLq84hu8Ac0a04G5jYT6AVTukTZ7afJ4NPvKU6PjUkIMEXmP8hc6uX4x2drZTtaN/KQGuICj/FGNqdkFhMt1Ymcz1m8/ZVsvnb0Wo37tusjrbDNEQ9v2KbtlWmlttRUedq8iyTtpjLbQ03WzxgGZOhVHiLt7dixJR0LXQrQpgrDbT6cEjUnQHO/o0lzY4Nanin2YkVjjVhnMy/3gkIN39LSqFfEVig/9NYSX2N8XdOpCDPjzd/lU6KGD9/wWwH9Sc5qdhrbHY1N/JuEZES070YXJ4+Nx2qHJiYs9XpzBb0tbyV2hIdo9gbMTkfoKQfzluH7ZiLLQQVpl5hNP3RjyaVyn2WNN71dy8EyG9AEsgy8BiwQT+B/j23A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: observability
