apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
parameters:
  pvDir: /mnt/ssd-data
reclaimPolicy: Delete
volumeBindingMode: Immediate