apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
  - namespace.yaml
  - redis-configmap.yaml
  - redis-secret.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
