apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 12.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: ha.gcelik.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - ha.gcelik.dev
          secretName: ha-tls
