apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: influxdb
type: Opaque
data:
  admin-user: YWRtaW4=  # admin
  admin-password: aW5mbHV4ZGJfYWRtaW5fcGFzczEyMw==  # influxdb_admin_pass123
  admin-token: aW5mbHV4ZGJfYWRtaW5fdG9rZW5fMTIz  # influxdb_admin_token_123
