apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: influxdb
data:
  influxdb.conf: |
    # InfluxDB Configuration for IoT Platform
    
    [meta]
      dir = "/var/lib/influxdb/meta"
      retention-autocreate = true
      logging-enabled = true
    
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      query-log-enabled = true
      cache-max-memory-size = "64m"
      cache-snapshot-memory-size = "16m"
      cache-snapshot-write-cold-duration = "10m"
      compact-full-write-cold-duration = "4h"
      max-concurrent-compactions = 1
      compact-throughput = "24m"
      compact-throughput-burst = "48m"
      tsm-use-madv-willneed = false
    
    [coordinator]
      write-timeout = "10s"
      max-concurrent-queries = 0
      query-timeout = "0s"
      log-queries-after = "0s"
      max-select-point = 0
      max-select-series = 0
      max-select-buckets = 0
    
    [retention]
      enabled = true
      check-interval = "30m0s"
    
    [shard-precreation]
      enabled = true
      check-interval = "10m"
      advance-period = "30m"
    
    [monitor]
      store-enabled = true
      store-database = "_internal"
      store-interval = "10s"
    
    [http]
      enabled = true
      bind-address = ":8086"
      auth-enabled = false
      log-enabled = true
      write-tracing = false
      pprof-enabled = true
      debug-pprof-enabled = false
      https-enabled = false
      max-body-size = 25000000
      shared-secret = ""
      max-concurrent-write-limit = 0
      max-enqueued-write-limit = 0
      enqueued-write-timeout = 30000000000
    
    [logging]
      format = "auto"
      level = "info"
      suppress-logo = false
