apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: eck-operator
      version: "2.14.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    # Manage all namespaces
    managedNamespaces: []
    
    # Resource settings for Raspberry Pi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 150Mi
    
    # Configure RBAC
    createClusterScopedResources: true
    
    # Webhook configuration
    webhook:
      enabled: true
      caBundle: ""
      
    # Operator settings
    config:
      logVerbosity: 0
      metricsPort: 0
      
    # Telemetry (disable for privacy)
    telemetry:
      disabled: true