apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: eck-operator
      version: "2.13.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    # Manage all namespaces
    config:
      validateStorageClass: false
      metricsPort: 0
      telemetry:
        disabled: false
    
    # Resource limits for the operator
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    
    # Pod configuration
    podSecurityContext:
      runAsNonRoot: true
