apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    # Single node setup
    replicas: 1
    
    # Explicitly disable master node settings
    masterService: ""
    
    # Resources
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "4Gi"
    
    # JVM heap settings
    esJavaOpts: "-Xmx1g -Xms1g"
    
    persistence:
      enabled: true
      storageClass: "ssd-storage"
      size: "10Gi"
    
    # Override cluster settings completely
    esConfig:
      elasticsearch.yml: |
        cluster.name: "elasticsearch"
        network.host: 0.0.0.0
        http.host: 0.0.0.0
        http.port: 9200
        discovery.type: single-node
        xpack.security.enabled: false
        xpack.security.enrollment.enabled: false
        xpack.security.http.ssl.enabled: false
        xpack.security.transport.ssl.enabled: false
        xpack.ml.enabled: false
        action.auto_create_index: true
    
    # Environment variables to override defaults
    extraEnvs:
      - name: discovery.type
        value: single-node
      - name: ES_JAVA_OPTS
        value: "-Xmx1g -Xms1g"
    
    # Protocol settings
    protocol: http
    httpPort: 9200
    
    # Fix readiness probe for single node
    readinessProbe:
      httpGet:
        path: /_cluster/health?wait_for_status=yellow&timeout=5s
        port: 9200
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    
    # Adjust cluster health check for single node
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=5s"