apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "8.12.x"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 1
    minimumMasterNodes: 1
    
    # Resource limits for your cluster
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    
    # Use your SSD storage
    persistence:
      enabled: true
      storageClass: "ssd-storage"
      size: "10Gi"
    
    # Single node config for development
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"