apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 1
    minimumMasterNodes: 1
    
    # Increased memory for Elasticsearch
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"  # Increased from 1Gi
      limits:
        cpu: "1000m"
        memory: "4Gi"  # Increased from 2Gi
    
    # JVM heap settings
    esJavaOpts: "-Xmx2g -Xms2g"
    
    persistence:
      enabled: true
      storageClass: "ssd-storage"
      size: "10Gi"
    
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    
    # Disable security for development
    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: false
        xpack.security.enrollment.enabled: false

    # For single node development
    extraEnvs:
      - name: discovery.type
        value: single-node
      - name: ES_JAVA_OPTS
        value: "-Xmx2g -Xms2g"
    
    # Disable bootstrap checks for development
    sysctlVmMaxMapCount: 262144