apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    # Single node setup
    replicas: 1
    
    # Increased memory for Elasticsearch
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "4Gi"
    
    # JVM heap settings
    esJavaOpts: "-Xmx2g -Xms2g"
    
    persistence:
      enabled: true
      storageClass: "ssd-storage"
      size: "10Gi"
    
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    
    # Complete security disable for development
    esConfig:
      elasticsearch.yml: |
        cluster.name: "elasticsearch"
        network.host: 0.0.0.0
        discovery.type: single-node
        xpack.security.enabled: false
        xpack.security.enrollment.enabled: false
        xpack.security.http.ssl.enabled: false
        xpack.security.transport.ssl.enabled: false
        http.host: 0.0.0.0
        http.port: 9200

    # For single node development
    extraEnvs:
      - name: discovery.type
        value: single-node
      - name: ES_JAVA_OPTS
        value: "-Xmx2g -Xms2g"
    
    # Protocol settings
    protocol: http
    httpPort: 9200