apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: elastic-system
spec:
  interval: 15m
  chart:
    spec:
      chart: fluent-bit
      version: "0.46.x"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  values:
    # DaemonSet to collect logs from all nodes
    kind: DaemonSet
    
    # Service account with cluster-wide permissions
    serviceAccount:
      create: true
    
    # RBAC for reading pod logs
    rbac:
      create: true
      nodeAccess: true
    
    # Configuration
    config:
      service: |
        [SERVICE]
            Daemon Off
            Flush {{ .Values.flush }}
            Log_Level {{ .Values.logLevel }}
            Parsers_File parsers.conf
            Parsers_File custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port {{ .Values.metricsPort }}
            Health_Check On

      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser docker, cri
            Tag kube.*
            Mem_Buf_Limit 50MB
            Skip_Long_Lines On

      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Kube_URL https://kubernetes.default.svc:443
            Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix kube.var.log.containers.
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude Off
            Annotations Off
            Labels On

      outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Host elasticsearch-master.elastic-system.svc.cluster.local
            Port 9200
            Logstash_Format On
            Logstash_Prefix kubernetes
            Retry_Limit 5
            Suppress_Type_Name On