apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: elastic-system
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: "8.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    # Resource optimization for Raspberry Pi
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
    
    # Admin credentials
    adminUser: admin
    adminPassword: admin123!
    
    # Persistence for dashboards
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: ""  # Use default storage class
    
    # Service configuration
    service:
      type: ClusterIP
      port: 3000
    
    # Loki datasource pre-configuration
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            isDefault: true
            editable: true
    
    # Grafana configuration
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: true
      auth.anonymous:
        enabled: false
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
    
    # Security context for Pi
    securityContext:
      runAsNonRoot: true
      runAsUser: 472
      fsGroup: 472
