apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic-system
spec:
  interval: 15m
  timeout: 15m
  dependsOn:
    - name: elasticsearch
      namespace: elastic-system
  chart:
    spec:
      chart: kibana
      version: "8.5.1"  # Match Elasticsearch version
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    # Connect to Elasticsearch with HTTP
    elasticsearchHosts: "http://elasticsearch-master:9200"
    
    # Disable security features
    kibanaConfig:
      kibana.yml: |
        server.host: 0.0.0.0
        elasticsearch.hosts: ["http://elasticsearch-master:9200"]
        xpack.security.enabled: false
        xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long"
    
    # Resource limits
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    
    # Ingress configuration
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: kibana.gcelik.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kibana-tls
          hosts:
            - kibana.gcelik.dev