apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.10.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    # Use SingleBinary deployment mode for Raspberry Pi
    deploymentMode: SingleBinary
    
    # Single binary mode components
    singleBinary:
      replicas: 1
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
      persistence:
        enabled: true
        size: 10Gi
        storageClass: ""  # Use default storage class
    
    loki:
      # Minimal configuration - use chart defaults where possible
      auth_enabled: false
      
      # Override just what we need for persistence
      storage_config:
        filesystem:
          directory: /loki/chunks
        boltdb_shipper:
          active_index_directory: /loki/boltdb-shipper-active
          cache_location: /loki/boltdb-shipper-cache
          shared_store: filesystem
    
    # Disable resource-intensive components
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    memcached:
      enabled: false
    memcachedChunks:
      enabled: false
    memcachedFrontend:
      enabled: false
    memcachedIndexQueries:
      enabled: false
    memcachedIndexWrites:
      enabled: false
    
    # Keep minimal gateway
    gateway:
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
        limits:
          memory: 64Mi
          cpu: 100m
          
    # Keep canary for health checks
    lokiCanary:
      enabled: true
    
    # Disable other features
    minio:
      enabled: false
    enterprise:
      enabled: false
    test:
      enabled: false
    monitoring:
      serviceMonitor:
        enabled: false
      selfMonitoring:
        enabled: false
