apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "5.47.2"  # Use stable version that worked
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    # Minimal working configuration for Raspberry Pi
    deploymentMode: SingleBinary
    
    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
      persistence:
        enabled: true
        size: 10Gi
        storageClass: ""
    
    # Keep it simple - minimal Loki config
    loki:
      auth_enabled: false
      # Single instance configuration - no replication
      commonConfig:
        replication_factor: 1
      # Increased retention and limits for better log ingestion
      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 336h  # 14 days instead of 7
        retention_period: 336h  # 14 days retention
        ingestion_rate_mb: 8
        ingestion_burst_size_mb: 16
        per_stream_rate_limit: 5MB
        per_stream_rate_limit_burst: 20MB
      # Local filesystem storage
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      # Ingester config for single instance
      ingester:
        lifecycler:
          ring:
            replication_factor: 1
      # Disable ruler for simplicity
      ruler:
        enable_api: false
    
    # Keep essential components only
    gateway:
      enabled: true
      replicas: 1
    
    lokiCanary:
      enabled: true
    
    # Disable heavy components
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    memcached:
      enabled: false
    test:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
