apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "5.47.2"  # Use stable version that worked
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    # Minimal working configuration for Raspberry Pi
    deploymentMode: SingleBinary
    
    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
      persistence:
        enabled: true
        size: 10Gi
        storageClass: ""
    
    # Keep it simple - minimal Loki config
    loki:
      auth_enabled: false
    
    # Keep essential components only
    gateway:
      enabled: true
      replicas: 1
    
    lokiCanary:
      enabled: true
    
    # Disable heavy components
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    memcached:
      enabled: false
    test:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
