apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mqtt

resources:
  - namespace.yaml
  - mosquitto-configmap.yaml
  - mosquitto-pvc.yaml
  - mosquitto-deployment.yaml
  - mosquitto-service.yaml
  - mosquitto-ingress.yaml
