apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |
    # Mosquitto MQTT Broker Configuration
    # Development configuration with anonymous access
    
    # Default MQTT listener
    listener 1883
    allow_anonymous true
    
    # WebSocket support for web clients
    listener 9001
    protocol websockets
    allow_anonymous true
    
    # Logging configuration
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
    log_timestamp true
    
    # Persistence settings
    persistence true
    persistence_location /mosquitto/data/
    autosave_interval 300
    
    # Retained messages
    retained_persistence true
    
    # Connection limits
    max_connections 1000
    max_inflight_messages 100
    
    # Quality of Service
    max_queued_messages 1000
    max_packet_size 1048576
