---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgAXJ2G2q/iKudeBtOfZCKrIAcM2hulhv830dZxDVmyriC5HBun+eMIt7nvS+z2s1vdvquRgfdDpEUDn6wLpjQYICPc8aKXGwUVqo5pvI10pembsGKNex4s69kNsIM2ovL5HPi/RsUkiICcCyAKWoWRY59TIabqa24B7ydhISJsndtxa7gsQ5w6gWJWMkPDoHn5ZhTnhv3kdouJHlPkKkMfBmngbYba21hOlZ2mrJLUPPb5KkrQJeSlCxf6XzILNCQgb0tOjwe8qVfS+uoYL11mRozHlqEo5WcCli9N5434Ipdu1v4UbMFylVXGV1iwAved/qa67/ykKyF28CjAJNBYWoJ30+2FIqD6vZ5B4C8U53duWOn8H9bBV5iNc43P7EkNx8Xp1PmovAjv7SZ7H+GTC7GrNYs1XUHJ5qG0BD+WODOdGoo1tlL0mtRm461gpHgvhk0E2isAvLYZ5IGkyD49ZK4FEs1c5J/scm0ei5LKG2+uMmTpsnvrQRvWY3pfFpSccC5Y3vwsOhPaNHoY34juXqHbUKjkEJ+SNOefZT3Da6Da3zRCfyViNAkiKS46qVyjNmFkECzke+rlRyoGjy2fW2LLkRnQ/TqEsdW2fliOrsa9bVt7OCjkUrEkqGjVuigG2CMwnlWsJbA9QY3/TAuk8CNW5htieWpaLNEsY/4O6xAPkvHuzyJyZn69DzJs2108l5ICE4u1PUPXXLJ3fJ7yqcsj/MmmyEqscgDzXbw9/xwls2BPzuYDQAb3OfRrRsNywObocCuq0x8u5Qd7W
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
