apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntopng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ntopng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.netflow.enabled }}
  - port: {{ .Values.netflow.port }}
    targetPort: netflow
    protocol: UDP
    name: netflow
  {{- end }}
  {{- if .Values.sflow.enabled }}
  - port: {{ .Values.sflow.port }}
    targetPort: sflow
    protocol: UDP
    name: sflow
  {{- end }}
  selector:
    {{- include "ntopng.selectorLabels" . | nindent 4 }}
