apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: factory-lens-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: factory-lens-api
  filterTags:
    pattern: '^v\d+\.\d+\.\d+$'
    extract: '$0'
  policy:
    semver:
      range: '>=0.0.0'
