apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-token-sealed.yaml
  - ghcr-flux-pull-sealed.yaml
  - gitrepository-rw.yaml
  - flux-kustomization.yaml
  - imagerepository-api.yaml
  - imagerepository-frontend.yaml
  - imagerepository-simulator.yaml
  - imagepolicy-api.yaml
  - imagepolicy-frontend.yaml
  - imagepolicy-simulator.yaml
  - imageupdateautomation.yaml
