apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.5.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: postgres-auth
      secretKeys:
        adminPasswordKey: postgres-password
        replicationPasswordKey: replication-password
    primary:
      persistence:
        enabled: true
        storageClass: "ssd-storage"
        size: 8Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

