apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: databases
spec:
  interval: 15m
  timeout: 15m # Add this line to increase timeout to 15 minutes
  chart:
    spec:
      chart: postgresql
      version: "16.7.21"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: postgres-admin-secret
      secretKeys:
        adminPasswordKey: postgres-password
        replicationPasswordKey: replication-password
    primary:
      persistence:
        enabled: true
        storageClass: "ssd-storage"
        size: 8Gi
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

