apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.x.x"  # Use latest stable version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: postgres-auth
      secretKeys:
        adminPasswordKey: postgres-password
    primary:
      persistence:
        enabled: true
        storageClass: "ssd-storage"
        size: 8Gi

