---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-init-config
  namespace: media
data:
  # Quality profile for 2160p REMUX with TrueHD Atmos
  quality-profile.json: |
    {
      "name": "Ultra-HD REMUX",
      "upgradeAllowed": true,
      "cutoff": 20,
      "items": [
        {
          "quality": {
            "id": 20,
            "name": "Bluray-2160p Remux"
          },
          "allowed": true
        },
        {
          "quality": {
            "id": 19,
            "name": "Bluray-2160p"
          },
          "allowed": true
        },
        {
          "quality": {
            "id": 18,
            "name": "WEBDL-2160p"
          },
          "allowed": true
        },
        {
          "quality": {
            "id": 17,
            "name": "WEBRip-2160p"
          },
          "allowed": true
        }
      ],
      "minFormatScore": 0,
      "cutoffFormatScore": 10000,
      "formatItems": [
        {
          "format": "TrueHD Atmos",
          "score": 500
        },
        {
          "format": "DTS-X",
          "score": 450
        },
        {
          "format": "DTS-HD MA",
          "score": 400
        },
        {
          "format": "DD+ Atmos",
          "score": 300
        },
        {
          "format": "REMUX",
          "score": 200
        }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi-lab
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.0
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        ports:
        - name: http
          containerPort: 8989
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: config/sonarr
        - name: downloads
          mountPath: /downloads
          subPath: downloads
        - name: tv
          mountPath: /tv
          subPath: tv
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8989
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8989
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: media-config
      - name: downloads
        persistentVolumeClaim:
          claimName: media-downloads
      - name: tv
        persistentVolumeClaim:
          claimName: media-content

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  type: ClusterIP
  selector:
    app: sonarr
  ports:
  - name: http
    port: 8989
    targetPort: 8989
    protocol: TCP
