apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.14.x"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    remediation:
      retries: 3
    replace: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    force: true
  uninstall:
    keepHistory: false
  values:
    controller:
      create: true
    rbac:
      create: true