apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ./kustomizations/cluster-sops-age.yaml
  - ./kustomizations/infrastructure.yaml
  - ./kustomizations/databases.yaml
  - ./kustomizations/apps.yaml
