apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  # Temporarily disabled until sealed-secrets controller is installed
  # - cloudflare-api-token-sealed-secret.yaml
  # - cluster-issuer.yaml