---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-credentials
  namespace: frigate
spec:
  encryptedData:
    mqtt-password: AgBviHGT9zqg7esRV0WbP+ZLCNEP4Bl/hQuCPsNFtj24Lv/TpgKo7f0cD75pOZYep8XBh5mVwwdmEgmRXGg76B2ytJJF8DCXkcKXtBICqa6eo672Tj4a/7dldAqVb7sF6S/pK0w5r6dSFIkxfeyBiUXadt8Tpw+/jdyKxmuU3zDYOzenZPRNJhuMmund9v5tXGolcH/kNh9OYF4lf63mlXgjuEhH74qThYDJSxLwWKqzI4SlXhbHOjQM+/brSbKCJ0CUC4uesWYl9oH6YLgJ4NzQyWvGOwCb+QQTdBWgFUfv+uvRLZdCFa2DNE7S0wDwEnr8CcTS9wAdnfxvPt4wjhSjMusVsvKtJq3/srQuqMiM9HsL231L8xwfgygJ+2w6lhFEcqX/o1ut/9RgSLKCkDjgz73B69sGBZNhPlEjokHS01zqYAYYmi8Ab7txgjVyxskFDgeFr4V/w/nRhbZQvxr9wJySKexdDT/RCS8/wf5EDHAzjHikRpLy2cT70eztEMC5ssXt+zo0QCZ6dNg5K0kd1aCAuc5aZ+VKdVaFafpb8M9LunZ0S4lRzxvzGgHsXrwfYPODO1oDnRTrI5DPMrc4Y20I80+3sL9NYPPBOI6xwkM63TLaCVLu8nat/mrXx+sorEGOZCqb7eJfbjm04NHM+mrI3QsNix18/ol0Z6VIGGj/j9hx3WtRzkugwbnOZLP4Zg6coJP9qtN7putHV0wZLrL8AN2/fCKdTz8=
    mqtt-user: AgBIprRF15TTMXFydJ6Up70fqBasLyZeHOXB4eU0Pkwscpy0W1NYlXXukqONggFiURpI34z6m7/u1kvaqjpP4csSRFIAZqfYqVX/5+hmeF2Qv8wPNZU7eQmECIpc72dF44AeUyuQ6kem/KedpgHwKWbwTUnFWeWrhAzIHgCDOfnGOijIRm2LjgJknSVLqZtFVcc6JtWsaZpU/TndiVlVV87DYKGwwqAKaCIcv42iKM9iTav/XBlt4x5JMj0CKO9TLd7elf25CXpZPf3oazje7yXG2OslGBI7TRhJNR635BscnuwYKJl1EcbSTKygeN6p/V3MRTG3hg0tz7ObE2hOYftcTWeHQb0B0Wycw/IUbKlKxFYDFJvbkDmffM7LvWXAYUP2B9gXvTLYK1497djLfPNvXMDiYx3EbT5EZgmw9Fven+NbBxJn/IoDdUUpVArX0VCUljvKU64qkOPP9ftDfZxpNdY/BIJ4hpmkXBYN3UGtW6o9DUq2JeE4TBtno0QFNcGEdHmtFRz8kxMV+LQ2UGIqG8bbZyE9w2s/ZiuiSbJdbJpjvmIcyBmFBc00jX8O0VSEgoCYIvif2n0UXOo49KH13aVNjj6/L13d24Rroa5afsFIhd3Sw4vjtMs0uELhVexhkbm6SENc5xXxkuc7Ft2QdBHcFKCnbNedWQN1cAACzitBGU0fKAJDn79T1VDKdZ1XWcwnXcRR
  template:
    metadata:
      creationTimestamp: null
      name: frigate-credentials
      namespace: frigate
