apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/home-assistant
      sourceRef:
        kind: GitRepository
        name: home-automation-setup
        namespace: flux-system
  valuesFrom: []
  values: {}
