# Factory I/O Scene Configurations for CloudHMI
# This file contains predefined configurations for popular Factory I/O scenes

scenes:
  sorting_by_height:
    name: "Sorting by Height"
    description: "Basic conveyor system with height detection"
    modbus_mapping:
      inputs:
        - address: 0
          name: "entry_sensor"
          description: "Part detected at entry"
        - address: 1
          name: "height_sensor"
          description: "Height detection sensor"
        - address: 2
          name: "exit_sensor"
          description: "Part detected at exit"
      outputs:
        - address: 0
          name: "conveyor_motor"
          description: "Main conveyor motor"
        - address: 1
          name: "sorter_actuator"
          description: "Height-based sorter"
      registers:
        - address: 0
          name: "conveyor_speed"
          description: "Conveyor speed (RPM)"
          factor: 1
        - address: 1
          name: "part_counter"
          description: "Total parts processed"
          factor: 1
        - address: 2
          name: "good_parts"
          description: "Good parts sorted"
          factor: 1
        - address: 3
          name: "rejected_parts"
          description: "Rejected parts"
          factor: 1

  pick_and_place:
    name: "Pick and Place"
    description: "Robot arm pick and place operation"
    modbus_mapping:
      inputs:
        - address: 0
          name: "part_present"
          description: "Part present at pickup"
        - address: 1
          name: "gripper_closed"
          description: "Gripper closed sensor"
        - address: 2
          name: "robot_home"
          description: "Robot at home position"
        - address: 3
          name: "place_position"
          description: "Robot at place position"
      outputs:
        - address: 0
          name: "robot_enable"
          description: "Robot system enable"
        - address: 1
          name: "gripper_close"
          description: "Close gripper command"
        - address: 2
          name: "move_to_pick"
          description: "Move to pick position"
        - address: 3
          name: "move_to_place"
          description: "Move to place position"
      registers:
        - address: 0
          name: "cycle_time"
          description: "Current cycle time (ms)"
          factor: 1
        - address: 1
          name: "robot_x_pos"
          description: "Robot X position"
          factor: 0.1
        - address: 2
          name: "robot_y_pos"
          description: "Robot Y position"
          factor: 0.1
        - address: 3
          name: "robot_z_pos"
          description: "Robot Z position"
          factor: 0.1
        - address: 4
          name: "cycles_completed"
          description: "Total cycles completed"
          factor: 1

  buffer_station:
    name: "Buffer Station"
    description: "Parts buffering and accumulation"
    modbus_mapping:
      inputs:
        - address: 0
          name: "buffer_empty"
          description: "Buffer is empty"
        - address: 1
          name: "buffer_full"
          description: "Buffer is full"
        - address: 2
          name: "infeed_sensor"
          description: "Part at infeed"
        - address: 3
          name: "outfeed_sensor"
          description: "Part at outfeed"
      outputs:
        - address: 0
          name: "infeed_motor"
          description: "Infeed conveyor motor"
        - address: 1
          name: "outfeed_motor"
          description: "Outfeed conveyor motor"
        - address: 2
          name: "lift_up"
          description: "Lift mechanism up"
        - address: 3
          name: "lift_down"
          description: "Lift mechanism down"
      registers:
        - address: 0
          name: "buffer_level"
          description: "Current buffer level"
          factor: 1
        - address: 1
          name: "max_buffer_capacity"
          description: "Maximum buffer capacity"
          factor: 1
        - address: 2
          name: "throughput_rate"
          description: "Parts per minute"
          factor: 1
        - address: 3
          name: "efficiency_percent"
          description: "System efficiency %"
          factor: 1

# CloudHMI MQTT topic mapping
mqtt_topics:
  base_topic: "plc/data/factory-io"
  alarm_topic: "plc/alarms/factory-io"
  status_topic: "plc/status/factory-io"
  command_topic: "plc/commands/factory-io"

# Simulation parameters
simulation:
  update_interval_ms: 1000
  temperature_variation: 5.0  # +/- degrees
  pressure_variation: 0.1     # +/- bar
  noise_factor: 0.02          # 2% noise on analog values

# Alarm thresholds
alarms:
  high_temperature: 80.0      # Celsius
  low_temperature: 5.0        # Celsius
  high_pressure: 10.0         # Bar
  low_pressure: 0.5           # Bar
  cycle_time_warning: 30.0    # Seconds
  cycle_time_alarm: 60.0      # Seconds
