apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
    spec:
      initContainers:
      - name: install-hacs
        image: alpine/git:2.43.0
        command:
        - /bin/sh
        - -c
        - |
          # Check if HACS is already installed
          if [ ! -f "/config/custom_components/hacs/manifest.json" ]; then
            echo "HACS not found, installing..."
            
            # Create custom_components directory if it doesn't exist
            mkdir -p /config/custom_components
            
            # Remove any existing hacs directory
            rm -rf /config/custom_components/hacs
            
            # Clone HACS repository to a temporary location
            cd /tmp
            git clone https://github.com/hacs/integration.git hacs_repo
            
            # Move the actual HACS files to the correct location
            mv hacs_repo/custom_components/hacs /config/custom_components/
            
            # Clean up temporary files
            rm -rf /tmp/hacs_repo
            
            echo "HACS installed successfully"
          else
            echo "HACS already installed, skipping"
          fi
        volumeMounts:
        - name: data
          mountPath: /config
      - name: setup-secrets
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          cat > /config/secrets.yaml << EOF
          latitude: $LATITUDE
          longitude: $LONGITUDE
          timezone: $TIMEZONE
          api_password: $API_PASSWORD
          influxdb_token: $INFLUXDB_TOKEN
          EOF
          
          # Create empty automation files if they don't exist
          touch /config/automations.yaml
          touch /config/scripts.yaml
          touch /config/scenes.yaml
          
          # Create directories for HACS and themes
          mkdir -p /config/themes
          mkdir -p /config/www
          mkdir -p /config/custom_components
        env:
        - name: LATITUDE
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: latitude
        - name: LONGITUDE
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: longitude
        - name: TIMEZONE
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: timezone
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: api-password
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: influxdb-token
        volumeMounts:
        - name: data
          mountPath: /config
      containers:
      - name: home-assistant
        image: "homeassistant/home-assistant:2025.8.3"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        volumeMounts:
        - name: data
          mountPath: /config
        - name: configuration
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: home-assistant-data
      - name: configuration
        configMap:
          name: home-assistant-config
