apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    app: {{ include "home-assistant.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "home-assistant.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "home-assistant.name" . }}
    spec:
      containers:
        - name: home-assistant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: database
            - name: DB_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-postgresql.databases.svc.cluster.local:5432/$(POSTGRES_DB)"

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "home-assistant.fullname" . }}-config
