apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: home-assistant
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef.name }}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef.name }}
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef.name }}
              key: host
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef.name }}
              key: database
        ports:
        - containerPort: 8123
          name: http
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: /config
        {{- end }}
        - name: configuration
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          readOnly: true
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "home-assistant.fullname" . }}-data
      {{- end }}
      - name: configuration
        configMap:
          name: {{ include "home-assistant.fullname" . }}-config
