apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
    - port: 21063
      targetPort: homekit
      protocol: TCP
      name: homekit
    - port: 5580
      targetPort: matter-ws
      protocol: TCP
      name: matter-ws
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
