apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
spec:
  selector:
    app: {{ include "home-assistant.name" . }}
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
