apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 5540
    targetPort: 5540
    protocol: UDP
    name: matter-thread
  - port: 5580
    targetPort: 5580
    protocol: UDP
    name: matter-commissioning
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
