apiVersion: v2
name: home-assistant
description: A custom Helm chart for Home Assistant with InfluxDB, HACS, Matter Server, ZHA, and HomeKit support
type: application
version: 1.0.6
appVersion: "2025.8.3"
