apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-automation
data:
  configuration.yaml: |
    # Home Assistant Configuration
    
    # Default configuration
    default_config:
    
    # Core configuration
    homeassistant:
      name: Home
      latitude: !secret latitude
      longitude: !secret longitude
      elevation: 0
      unit_system: metric
      time_zone: !secret timezone
      country: NL
      
    # HTTP configuration
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
      
    # InfluxDB v2 integration for time-series data
    influxdb:
      api_version: 2
      host: influxdb-influxdb2.data-storage.svc.cluster.local
      port: 8086
      ssl: false
      verify_ssl: false
      token: !secret influxdb_token
      organization: home-automation
      bucket: home-assistant
      max_retries: 3
      default_measurement: state
      exclude:
        entities:
          - zone.home
        domains:
          - automation
          - updater
      include:
        domains:
          - sensor
          - binary_sensor
          - switch
          - light
          - device_tracker
          - climate
          - weather
    
    # Recorder (local database)
    recorder:
      purge_keep_days: 10
      commit_interval: 1
      db_url: "sqlite:////config/home-assistant_v2.db"
      exclude:
        domains:
          - automation
          - updater
        entities:
          - sun.sun
          - weather.forecast_home
      
    # History
    history:
      include:
        domains:
          - sensor
          - switch
          - light
          - binary_sensor
          - device_tracker
          - climate
    
    # Logger configuration
    logger:
      default: info
      logs:
        homeassistant.components.influxdb: debug
        
    # Automation
    automation: !include automations.yaml
    
    # Scripts
    script: !include scripts.yaml
    
    # Scenes
    scene: !include scenes.yaml

  secrets.yaml: |
    # Secrets file - values will be populated from Kubernetes secret
    api_password: placeholder
    latitude: placeholder
    longitude: placeholder
    timezone: placeholder
    location_name: placeholder

  automations.yaml: |
    # Automations will be configured here
    []

  scripts.yaml: |
    # Scripts will be configured here
    {}

  scenes.yaml: |
    # Scenes will be configured here
    []
