apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      initContainers:
      - name: setup-secrets
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          cat > /config/secrets.yaml << 'EOF'
          api_password: $API_PASSWORD
          latitude: $LATITUDE
          longitude: $LONGITUDE
          timezone: $TIMEZONE
          location_name: $LOCATION_NAME
          EOF
        env:
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: api-password
        - name: LATITUDE
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: latitude
        - name: LONGITUDE
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: longitude
        - name: TIMEZONE
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: timezone
        - name: LOCATION_NAME
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: location-name
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2025.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        env:
        - name: TZ
          valueFrom:
            secretKeyRef:
              name: home-assistant-config
              key: timezone
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: config
          mountPath: /config
        - name: config-files
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        - name: config-files
          mountPath: /config/automations.yaml
          subPath: automations.yaml
        - name: config-files
          mountPath: /config/scripts.yaml
          subPath: scripts.yaml
        - name: config-files
          mountPath: /config/scenes.yaml
          subPath: scenes.yaml
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-config
      - name: config-files
        configMap:
          name: home-assistant-config
      restartPolicy: Always
      securityContext:
        fsGroup: 0
