apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/home-assistant
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: "2025.8.0b2"
      pullPolicy: IfNotPresent
    
    ingress:
      enabled: true
      className: nginx
      host: ha.gcelik.dev
      tls:
        enabled: true
        secretName: ha-tls
    
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ssd-storage
    
    # Home Assistant configuration with Matter support
    homeAssistant:
      configuration: |
        # Loads default set of integrations. Do not remove.
        default_config:

        # InfluxDB configuration for time-series data
        influxdb:
          host: influxdb.influxdb.svc.cluster.local
          port: 8086
          database: iot_sensors
          username: iot_user
          password: iot_user_pass123
          max_retries: 3
          default_measurement: state
          include:
            entities:
              - sensor.*
              - binary_sensor.*
              - switch.*
              - light.*
              - climate.*
              - weather.*
          exclude:
            entities:
              - sensor.uptime
              - sensor.date
              - sensor.time

        # Load frontend themes from the themes folder
        frontend:
          themes: !include_dir_merge_named themes

        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml

        # HTTP configuration
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
    
    # Enable networking for Matter support (configured via UI, not YAML)
    networking:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW