apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/home-assistant
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.0
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: "2025.8.0b2"
      pullPolicy: IfNotPresent
    
    ingress:
      enabled: true
      className: nginx
      host: ha.gcelik.dev
      tls:
        enabled: true
        secretName: ha-tls
    
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ssd-storage
    
    secretRef:
      name: postgres-ha-secret