apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/home-assistant
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: 1.0.20
      interval: 1m
  values:
    # Override specific values that are environment-specific
    # All other values come from the chart's default values.yaml
