---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tesla-public-key-secret
  namespace: home-automation
spec:
  encryptedData:
    com.tesla.3p.public-key.pem: AgCGlZdetPpp+G2GZx/di6TZ04jBRbK496TM5zK/TjRDx2OIzw//rtJI+T71zVSB/MHmfiFvbEoj44B3yOnnpOMVKyJ5ugPPkdTC4Q+pK8WwUgQ85mxPVO996VDtiCatINIKPeX8DKgMCaVQUH7UhFeHMj9pH0kPZrsYms3w/97T70Y8h6WjffzEuvTZA/da4xV4qCxhNzeInjYdvs+6SHqF7JAViTE46Qz60F76UPDsNW57/sT1AAnm3VJKUc2Js+ePb5sz2gv6gdte5Vc3gv7C5ElbQ14Z6ujYQGzfDK163LV9BLUJLG2bNhdzH8Jap60UHOM9dUlMNni7ZD0EsWzGzWehmYZ0Me7Boud6ue/6+xUkm7NGGUXN0FDFprh+AU+TL8fd+fHzg14Z9q5XrIJmdvgriuJG48aDBcsfjVvfAMQ9bfWzufQPu5uiDohsmQSwnbmhHnKgrmeRjKMwU78PYLP/cS/DeR7NYatC4EuXZQISkbYrRkuC3By2B3nqP7LYLneMEVdZBu9rCUWwKU5OndJwTy+N5UnU2tkr3PSRH/fA8rnifzRwr85/rVkkLRSGnuQRyaaZUQKcfRXxan8je8trkPz5jarpi1wPFK6efZElK1Qz5sxklKso3tfJdk1kB9/rlimEJ+fGhMt9PYeEAXHj6pZgd4RKBtkmctMjUuBuHXucxlWv72Kf67LZeQZrbi02dSIuYVeTOCIqVCtoetrujwG5FR/a0qUPKP56okrhb0tVU2F3P4Mh0SbumKO0Cbfpf88ELrGaE6mVwdHLvspbJNRt5HTrhaFFO+EcbM5qeHfVcYRey/Kj0BXFE2WfxMIkebTdiWD86TMqRqnnVPIT++cnMNq70gLiEEGpOw6xjdebRLBZOZqAfjn8NFXallf2hyTMxDELfdoYUBQi+0WEnmZmQUCV4n3U5XIl0XPV
  template:
    metadata:
      creationTimestamp: null
      name: tesla-public-key-secret
      namespace: home-automation
