---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mqtt-credentials
  namespace: zigbee
spec:
  encryptedData:
    factory-lens-password: AgCjniaJX9Z+DNz660SSejTGLbGqXRrQvGKkx1YAAU/ArkOmKFMLuG0LAzpa/zgQ00ZHIdYweL2wmp/oAMDMDNsSNXq6Op4DseWEREllPZKsZnYQye77vGFY3zj+Xpeb6wN5vpWAWoNyudJN8XtFv5hzyEWvXxtbAq/m1g6zilgWmz3zbucW027VuY4D5l1HafkwX5LP5I8E6gJHVCRHTlcDDCaVKLvf/1NKNbsnlUX+Bv6goW4eNogPU5cGAbZLMJ4KVPYcj3XCFlzoTOwlHDSZy7asBJ44ABT0NhBbaL8ZHO2EFo8qoFQq6W5tP/kyvHu+xKjCXXqvtyx1PMOC7TRk6NFQfxV63IA/jSEcDP10AbMQHpJT3KF8G9rler0xLTneeJwocH8P9dvz1PFKxWSunbG0rOVCgnrsCFGYOMyUREBMgVbeezYzHmPOJTaoo7C0n51nyGtJw9u+0Pw0HjDZa+xsRVdYQj1BZqmdDvMD4LMrJ7HdEv+4oS9vfuMSOlQ5+k8lAZ4/y0Om6s/2Yif2Bw15ECXyMHEoaaTQ6BZyLTuemEheOaMbKjUTc++r9bZj1l0MVLH15Tj03HntcKhV54pfE5EJ3HT1qeeLPlD7V7Bl3uBxJOaqPVvi5qiqLUT4ub/JDtIvo5hJdDOt/3WwLxBa6/k2IVcTiYYHQoc87GKHHUmRqj7aTfuYfOqwf08C1PFsA3Uk8y964TrSCIsMSwY7LU3HmIhECsHz8RRrICZxrBc=
    frigate-password: AgBYy/kkvrIPpNEzZI5dUvuvqHTd5g25A18sqfz2hw4PYyl/7m/IkCPepTlX5/ft/i/ALEU77lxgsfldGiuh3t6qs1W5q5s2qM4DttnORgNW6n1jnmND93DY45X7ju6rEJDcYEbg0t+DTWPJbadJDlLTic4Rmjmymt+9i9vRgYpzLdFB/K6KrePE8zh1TOVyBEajIhKbk2uEy+7JpVqN5CtHL1ilsggZARxWw9mdLEF4luErzbQnJQctH2ej4bvtNcZ6xlcMhoD4aK6pp+C+cs8i3Ab3yJ0d0QMGEBuZ5lmeaT2K+ubVIdsoYlrpI5nmUvPl2ZAnIH8FpfXTnzYRUZntN3cW92w9sGx48zLKu9NShSt2EmiukTRZXWeQw3fcPjLx3vx6PILbcNqbKyb+OIVYLyZT+Omy36wI81QsVPH1iiPwZNZCotBP3GFdR4MJa244tLgQg4Ooao+8/yEI/mqL8qIc+gN+GfrO/cAuIFvDHWIW1DZvrMmG9QTRSTXzPrEvWd+BMd4CIpbmfmwVuS/GS2fd/2zK9+AJoQULbMDoANnnEnFcMGJN1JobIUFM08QCOJe7uz3692mPjO6MtwmwKXzp9o/lGzjJiOAVlRCtdiQvI/EEwA0oO0QnfQfPy1tP626lbQbUHJuQY9FiQ7b7fSolUr+v5RYK53OW8SA3SYiFLeTOogRNys9S6o8y1dnWVqgEaT3EL3N/UeK1YFpbsO6OYryuj8bT
    homeassistant-password: AgBJS4qxvM7uhETF9I7n75v7uyOl4alkXanyjM4clLfBBF8tQU5/3qxfT4ckvJUWCAVbmOHPy7x66jKLg3i05ue9nNlKiArJkzhGcH7TnWW7rNSBzcJeSspdwS59PTE9Z7NuRpXbED2PSqrqpLrbmHFFz0SI5Rc3aPIZtojNSBkTmq273o7m4+UWGbmrWvAEcHWVj/TuYSpSyuXaQR2CyiJ9C38Fpzayf+Zd5AQFfz5VsLupFFfDMW3qpDGbBx8juEfkWMLOf8GTEnX9O/xK6fzsyCF6MEdSp7hsW2UbrR2HiaQw8ughbrxJO+ivWiIzzALVLCaPj6xVW212UYfVpmWQ/jDWUypvWijyZPv22tdj2flIl3Ui73MjBTd8e/3DNoLzZV+j9aOuvqiboAQqTqRQCNJhGySn2S+vEpqE8O4lGA69fvMvvG3MM+bNXxzimNYquLkRDKvYydVEbKreYnIH0fdZpdjS+/fI6WObLAqv99uhLGafP6Dc8YabLr7uT0tGn2aUOjbetFdzUcLdbqNp7d3AABg9Sv8NlRCyk+BUFI1nHVg32xJ1TYUvkmBujuQzKx+rdCLkDL9q8akEToukspQ4d2pVQ02ptnhcOMlUKNbaA8BUg8qWTFg+z02d+otFmkosiy3vM42ECiyRZDu9z7r5dV+X3NkrUxRsZWZxGegRn/+NSI+GgyVX+ZdMhKXKye4+wXbf5E33+ECFuPRdljWELaFGFQ==
    zigbee2mqtt-password: AgBiWquNa9nGhpyWn4oP2wT/Hiy5Nwtmj6hZvRzK0uLfyjgN80rEw44katKVwIe14pn6n6QK2Ph0Dkz2+QEaG2W/nbBQ63j4FoVb2rgQ16pe4uZ0trpekYxtsSTgoqRs6o6fU80Ni4PZSEwPr/rYShDEZ0xgQe7xfEF8z8MheDdxiEXs9FE5KwapE+qNxmWWmNO7uc+BK5U5rzDvIEX5p0csOAJJzK8oYNiR8fsGwnpUgKxrueuuqxnKDcvciI/cIKiT+4i/p0MX98HMeF4ifampQogv7wYipokwS8/iqMQ2yQVAgtj5CQAEyixsrCMNqzXnEqkHO1EZ41Q6hd5y4qUMsO00fnr9JckxvoXFYwGwvKg6NWC9vv8CT/j3ojXdygDGURkQr0/Q2X+XipyLyQ04sElclJ+Z1XvuxJ318wHWaQdLSAiwUOYNV22QK1Mn/1crUR35h4vc0Md35SmJ9ynCsgC3XCVap1SIpulh6Ma/RtTJxWVU+y/xPgwfuJmvxtAJG1zcN+tJtbyxV4kT3i/BabZs3HW2qOy146hwOaN8/LO0kwRKaP4AaBGi9ue87SSQmVz+ECLiAeGGmHyWLAkajefUz7JVKA2q717NsOMCRDpQLuVzaWBGG06Rj/asaIQDZEs2tYi3bccv0aR9B2ojLs+ruFf2p7eyLCRmhNpxoz9xU9vwLF7dum17Gly9Xv0htPqGuIuqgyllGhmZgHxfEhZ603MaKjOq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mqtt-credentials
      namespace: zigbee
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-credentials
  namespace: zigbee
spec:
  encryptedData:
    frontend-auth-token: AgC8D3MlBID262yJIHLn8I6cqhUPayd3485dVloTZcJQIi8uYHKI9JIZb2wDWoLM1vFCd2AATVJiECHGyZie85NzALzRw4HDSGi9OrnusQGfAT72JpVmTkw7bOZEtcvJ8bm+6zXkiT4ABiTzbu1XjBQz4LnlcuAOf2LPS0reYGLSgsmEszjaXUUWnFhHJ54XpopyPHtjiM1IogZq/Nan0VzLf+JCUOE7OuwukbJHbdPgCJxVP7f5dbm4kKZBWRuEFtcOsXJ2k/R0FA895y9ce/q2L1WZ1wWai3pVWJi9o0inyaXzIwzYB4sHJIu8kmJVwf3z/YLXFN1hxJRYdoIppiSD8rFTJlz0n+Ecg9l8vlp5NM9o3Pl8aT3EBwzBmnL547NsSFfNpxPw8wA0IdMLUlMuMj74uqYHcTr7m2SuISGMuCgHObGSTydsQO36fqIlPIWgcENmTJHQncKVMdst2QX+E0Gq2zQi6find8SSo1SUerjOWeJjN0bKO7p1QcoTXnTUILMc94dt1TAHSD1GdwGhk/7ED28iu3821t6ldPtsVBT0ZIeV/MyoTU3KUrZ+fi7zjEqZmIKUBKf4onvF8FaY+pKcSeB3SIO5YeuJ34ZQaTtMFEd5rsXdJ6VNNA7uRztHM0VX4AkAeIX0c84yvzS9k1qFT8LHvY2AJkH8Vz4yYL2ck+vs7uPlSIP0vpMgAr36A2XdYzlTrNEq7nyyZ45FI7lz2GsN+TTciC5Gr1PfX0pDag==
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt-credentials
      namespace: zigbee
