---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-credentials
  namespace: zigbee
spec:
  encryptedData:
    frigate-password: AgCygslvmRw5fNF08NB59duY29/pAd9ObAinAeUFJFuvYDF0TvGEdrqoQIonHaDIk3A6WKF9zDSNrX1afiX4CaNdWKc50WQFPWfmrZ2hLkMY76UD4foFPuKIt0wlyQQxsPPk5MhLKltU8fuWNmzSqhxJcszok1Ie0Fnrg+Dupqa3rQ9b9dXUQSC4e8WvvWhSHeHEtARKpkuRCifOocDuhnw2w5i+OA/fCu/SjBi0uiiyBx+m3BkN2sIWjPlCUrzYhmjJgVCChapzu7AVkhPhO9bGpljmfNAiaWQ396HgFCYOb6JcEmlicCJyyi7KHeqeq7PJB43/HyqR0sT5BcTNDdvwipdtDo/5yu8+3bsJ+ru/Fv1441+UCx1+a6uiUw9ea0MFSaSH3Pa65WGmlmkz2iPFvTfM7iuNitBLn7lvT5p3BNs9DZUZ06Ky4fb/sigqL7OWR9sc5fiTpc7MA0Kjo/7JqhGJNZh6gsxL3QcnMs3z1mo0A9AdtPsWj9zkX+3aiK6SHxd3lZzXntlY3n2GHRWCnjIL3GZzVNm5R1rGGXr7p4a7bNH1fIBUO6Uz5ttOpBHLKa6LKDYU+HdQB7uAnTUYlW0WeVfrK9u+W9exqwXD3rSEanX0muWnjaH0pMNS/2Y8hAUR3T93QMVBA7nus8QL8o0/h2CxBer+qwI58tu7RJMqkRfsAa1n7QN1Roz6mGYcww2c4oa2fuG+A7If+7wTK4kJSRWThqLi
    homeassistant-password: AgCDffc/8akDviTOuWSv74laxOvDzFel6jgoMGQRl9AS5m/7K1W744fj0eF///QnX4PtAO2AaZ0xMSojc2HqBsAW/NVnJlYgMDxLu2y4Gn0wXuqGjZMX7qhDHD4OHzi6rMY/L1LG2nUkzATJy3kfo+FLdfyKmhh3o4gaGplubi0lN8vxYJMXffEH1B/f5qYdfb+XDkQZsaWVTALptZxkEwwqCpBPr3ua84a2cOBHx8cR6MPyDM+TnGft6uws6SThaMz6WPG9/QaaVJZtgelVa6jPjvjkqrUgXHnmfNRwXlRboCB7GfU2Rk3SjwX7zx3SHkCZEL+3BbJKGchodiE9/+nXkcKgk+5tVJZrtj3luGgle3NTFNEy53zlwEF+hprkAuTv7yIfhLKBWHBnSy4YxxEcQWRzyZs/6IdSGgnRy+Zx97ppnOQpbRtxWYOwPK+aVLAgPXYdNq6ESLr8L49v8qi0PmhcpEPFdkthD8RAYahCTqL1WppJk+Q81nu7j/3r5nNdZL8qL5YBlMw3AT7m26yeKl34VztscqN8SDdJwI+g4rva6y4d5yyLrSVBFLcJnz+rDfFCwycLpuA+KFEV+yfFgSAMXU6lLSSvrFmSt6vN8nFFCW1lW27LcNc6AAwy2Q/kxW52O0Bpti8HTg9is/Qmr36+Saah74BrFmmxnpKHzIB5/EGhCYvwmeFomq+XvcoTYZgYe+hpNmzPdO5X8K375zTV4tNgMg==
    zigbee2mqtt-password: AgAImTAHxtrqcblEEOb4vsXw9Fn58BXDdjXvngZ2TTlZUqibHihB4iMx8t1QEog3Bo7YMBMDjZYRuvQPS7Z7pj+m0BiURWpUyNhzMT4CY4hulMplpAQSL7bXBueDXqIlo+NKuzOkdMcVzzH0AgR/8X33yktoSBedylQ20c5WdHjtdyMW+yDubLYlM4TnrK6kkfSMJ0NMTcHzcRblS04lCLQYDrdT59dXBw2R17atsRp0WqXbfKmEWuQqv5stURbwlz4St7dv3AG3Pdo/rRujuomFsI/06oDHQZjhuM2hpzJqZ2C4p4od7xEhi85P+uyd6otdBdQUnaq0OXjenld81yN4wiOEcARlRD2qpf6LR1YVbfGc0OoCwLYeNRz5v36OcqPbp3PDT6413v5ut++mJx4rq6KEWXd1Vyo/Ul+rQ3oHUCWKc+vckidnRY6wFdIVpf7lI5jBqK84WKKbsZQCYRW+O3ONeE8m7vzBCdve20lThw84tUEqSS175ela1fkBrR8TLnnyEGPpWVAJPEJ/LvkyGtf2sLiN2ihnNIE1z/2py8TGffMd4+2ZEAjb0kklZ5BB6xlxnEtNqT3DHUuabgVFToRKcu46u8syOsNAK6uQmXx6wagFvPfEomGC9DrfW28kw+zmhXyNW6gGzeF+zkS6E/kniPCMQ6gXcgvLojGyOsmcjckaSSxRY+k/eLDx+OxP61yV7K3QnE45rF0h6iLHSQpFctaIus+e
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-credentials
      namespace: zigbee
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-credentials
  namespace: zigbee
spec:
  encryptedData:
    frontend-auth-token: AgABsql2TBr2wTYqlJv7mvh/qoLBz7qnwzv1yhgnQHW6Y9y5dCcvwCLLuMEW/aQptxxZVEIN43A79qM57+Ge60UikGmwEnb+Pjhen3u66AxHUjkaDBN1D8au8fICJnWemfoDNI83l8XqyKdm6ez4u36r+w4awlfUkR9N8onkohzK7tQ8SPBbrM7mMS5yp+A1IihPM1SJn4F8HUnzc2i+a62xhvleWr/0RZU+F+1o0VdjKTuDUtHyIFxzbFpkJAh1plr0vEWTvvESAjEqouylZX2ow+1RD54RnNRworRWcJUuHLmK0LuC3ZapAVL3FpSltEjN2dOtVhLkrbN3DeK+dwcw8v10xZsKEbClv6IaJXH6h2f4U+FLwCFjFonmsRQn3KeRysRixTcUa2fSg0mWCZS5fBnFmeAQ9mEKHi4VM+UBDsr/EFpXpqAHmtpjsNaBgwiJMRnAw2q1V3blXGxIB6cGlJPe0j2ok5nCG89fQp1LXg4iL6fD+tQCyXL4XldEWLLjNfFL36j36z3KO/SXnzLexPf4meWa3+sHLUgz+CGZ5J//VrnTgnOFuT1pRPytaoddXlo+/hjhOLI04F+1gA9Gjf1WCXiTWPmvO4lhvd8AyeuvN0gdecJyQEAG70og8HbpTOtwskL0uclFmr/tsvdINkaKgb4ix8R2DhLFy8o+56azWGvOMdGQOnnUshNCyjVBKg0geF4bDQNfUkeMPed2GZwHvl/qoK4/1zisN3+QGc1zBw==
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt-credentials
      namespace: zigbee
