---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-credentials
  namespace: zigbee
spec:
  encryptedData:
    frigate-password: AgCLhTPhID3m0xi1TDoZjI7fvo1gK0xF4ondVCmlcrUfQKEX6FF1HkCSGRmD9dPTLmxDXJTMCM904wqb/ENbJrIvX/DUhH3g6hGnsCutRPesoIcX+aGQ1uYBkB6zHiDE2mjkI77DKkaV/FXFnkJuN9PPX66Yco35d6/9atyHPO/1T54Fci63qjOqa5bGX3jMrwD6gbXcW3bXe+7TDzatoCSmr+JS7PUkWh2bbabZXIQ3t21dDT1kH0pey8tYoZgiR4/Kuat5dQH8dSgYmmR7YlC+SZJ3JzQZE0+kQ0+duRZs51BY3Iv+2yFvjMR0sQBBpABsfliPnZqM9uNroB9/1SOFNikFXuCmAXxWGQyjKhIT12FMB/zDHIwG4HweWKmc0+W4OvD2KxUnwSEqiQ2mvt2Ikcn7Yz/uRAiEb3H1KI8/F4kgkU8zZRfbHoIjKiXh4InmKjCWfC4PPikg0PEYQ+RIR7koswdpcgBTgHyPOzsIY8AlvUb1ednClhh31U2KmJcLz/uae7foY8sRdcwxrrZ6NmohSBz1xDdy+mUIPIwvvAM6WiZJ3e1DMudF8ECqqOwV1zy+FiIuH04MpQ8+RfpnvHGePvedfC7mzp2Tljl40SdDJryiocaNJu8g5eL0O/RhaRVbvZMjY+NvBXlrrh4/740kwehWdBo/P48FdiGH3DD2EOv4/ZCFjkbAJTchWLVHUbCo6nzWMcwO3JsSPOynwZlaSe9gwIne
    homeassistant-password: AgB2Qvz+rdPU5az3h+QZiCPl6BjSLDXF1/lazCzEcqwEkVXWikdTuGlUKQA9V5Solebr4vtiUJ8360ctONG0BGKmXRCz9hZtTLSbpX30v6RNdOJ145GF9JQ2X2F8v3Ml8CGyXOP3m8jhGr5d7j2JIVS5wzlkG7/NzvY8ZWGKC/LQPAP7CNR1zdVFPZ2lLgU7UpwYuj7mt+SlOydBlNKeDtws9zh/7A0eUMRfFpvDrKEdfjliRhpIz4cWsxl8XzGg4+SlL0POEJDgJc654+cV2J7EKVuH7bbY25i5NBXLE2Gussyg8UcL3Q54JMa/0rJjndyX3V57s1vIP2ucg0GmCOvMe2dGeMA8smpZTzR01/vtWChjsHsDksRi9EBcH7/33asVwcahxxyFQaAXaUNQfU4tUA+0sJg9CYf3tMgc630wp8QWmzXe34Ax27OSsIzzE69B7/6oAOPeaexzOhMIcsgtpQShY/b1ThWK6s2XY5Z9uyOTBNnP90KjAuZ0e3jiRXhlK0GZ7s8YL9wEkMoZe4JYTlbcWbgo85jZw6uGgC5AJy/2fUfeB2UWxlw+pLKoPrWQwfcuIxE+/c3WsVjLEjbUInZ5ZHnOxcqUKXKHUP7JvQrX3LBj/6DAObxebOJ6JbC4rcp2bKGUIFOKTgKFr72nxd4aN22ggGO1wizPuqG2AqMWdhk5nqwqHjAParaGGUdShrXCdjeSkdrK2a2IZu/S1hZxK5YhIA==
    zigbee2mqtt-password: AgA7FkAZ39rsonZ+Wn28WwLUwrwyvFLrW28DO9WWzPwaS7kcd47YvaM6Bx0QBMEK7pysMEyRJvrqWmXpZ/zXxoQbqOBS8hAFyZQeiZT0vgE78gGIxfxeFDvHc+SVNWKzQu2DzPViIl9plR3PVMXqUBh3BKFzREqhorkRLBzeIoD9BW48EBvwWUojkggf6HiUZZ2G7JQThIwLvgowjFLg4tb7LtYItlBC5/8a1g3WjHQTeStDLCvLdpdPtXVaQbLLizU5AxvqxQ1oXTTdSMdgqm0FArDBLCViWNYtpiF7mH1CviwfO29oUlITjtyanMhED1vdY+seue37l2ZKxhJb+8fPKmgtOeWYMoY+LjzF+JDrp15HKpibKDC5Fnv6dA+S6lQzRNB7yGaFUEfU7pcucovz44kvdSs2QHzcD3dQi57j/rzuuGsurx9Ve6BUF7CqYxQtlxp9itUg5gu18ehko6LkY4MwYl6ctSE+gcTywH5XrqVvJpvYFG+IOjex6Itmb+0Kr+6wgqA0QBgecgb/JcbCoNozWTTtGUCuX+pKQrYYXt6NNjNlD4fex9wNHUD/5SXtVTzPI8w5MpQI9hG5pSqEQH06kzo/HkLjtZGu+KbuG0ZwuQZ1USn7BqNm4iWuMRweYwPQTxsA3q0YCWxE8KqJh7NqxETzB/j8a+Y80btcpGwVdqcY4PNriet8CpobaUHhpEY68Coo6RPmeBAF7Ntzy84piUa1ZcQq
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-credentials
      namespace: zigbee
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-credentials
  namespace: zigbee
spec:
  encryptedData:
    frontend-auth-token: AgC8D3MlBID262yJIHLn8I6cqhUPayd3485dVloTZcJQIi8uYHKI9JIZb2wDWoLM1vFCd2AATVJiECHGyZie85NzALzRw4HDSGi9OrnusQGfAT72JpVmTkw7bOZEtcvJ8bm+6zXkiT4ABiTzbu1XjBQz4LnlcuAOf2LPS0reYGLSgsmEszjaXUUWnFhHJ54XpopyPHtjiM1IogZq/Nan0VzLf+JCUOE7OuwukbJHbdPgCJxVP7f5dbm4kKZBWRuEFtcOsXJ2k/R0FA895y9ce/q2L1WZ1wWai3pVWJi9o0inyaXzIwzYB4sHJIu8kmJVwf3z/YLXFN1hxJRYdoIppiSD8rFTJlz0n+Ecg9l8vlp5NM9o3Pl8aT3EBwzBmnL547NsSFfNpxPw8wA0IdMLUlMuMj74uqYHcTr7m2SuISGMuCgHObGSTydsQO36fqIlPIWgcENmTJHQncKVMdst2QX+E0Gq2zQi6find8SSo1SUerjOWeJjN0bKO7p1QcoTXnTUILMc94dt1TAHSD1GdwGhk/7ED28iu3821t6ldPtsVBT0ZIeV/MyoTU3KUrZ+fi7zjEqZmIKUBKf4onvF8FaY+pKcSeB3SIO5YeuJ34ZQaTtMFEd5rsXdJ6VNNA7uRztHM0VX4AkAeIX0c84yvzS9k1qFT8LHvY2AJkH8Vz4yYL2ck+vs7uPlSIP0vpMgAr36A2XdYzlTrNEq7nyyZ45FI7lz2GsN+TTciC5Gr1PfX0pDag==
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt-credentials
      namespace: zigbee
