---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB/w00zIy2nFY25N1G9RYF8HjSCzBc0gzC8XHEWbzBa8yWhGMiMEZVfjj6Das4RehyINSGLDX20IjaRl5TWfYcM9iiMnDEPHPThU2+s30TfMbfch1KHia36IWADbjXiODJ1ZrpCrExdoAAF2onn8TdUUpr7G6nrK3giKQ33+05R42IqJhP0clWi8Mvbm3chJ8ga50Ux6W2tNyixYSOf2T430OlbL9sv/QIorbd5d8YoRDxLtgVDuXO1DN1Vg5Id1DFXXeDbagTZ4vUA+1oYQfSZwO6hS0knu8ETaCOVkSeS8fViREp8uWg/meT6JXBFQUjR9+0GQdJo134Hr5K4cPE/1BG0/bA+1PgmR3Z+wMalUU0DoM2XQ0MQuL+GFzd865OmCOzbRZPxP1Tpddrsti7NHh3j09fd8dYSH5TCk8elKgAqj6FQ50xLR5HuHyvGbxiUxOrUjYwBeSG8/hFvr5lerm4b+6MgOWXsl4I6v0Y6mWE9n/LY0Xc9dBPqxrejvbrUcit3O9qr0xQiIN7EfiJZgWbx/XcxUhbOwJfdW+o0UKdTgzJjKQjdsx7SlsCG5dqJsaMDul+U0by9QpG9WrLN4p5mfwFYAQBunwWCHs1qyCTtJODaum9XqzlWfYyaMUexpWIpNWRcUuUA9eiAViddv4ZgToCytQ2YfYvoRsqlc8M+qG4kyOYzowNW3uqkvariQ8588vEjWpfPt5vtAO1BHOxxzyPnZFzhqQFTKncT1eWAGZ1yQPMXCTejtG+I6DBbZsr4ZQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
