apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCOaoyc3mc73MoQ+nv9oxI5JVRv/qiIkynWtbf0EWL+kuortXL4NHL6vnjS/uxhF4mZZqwSRr8x+0LLFQsGicH8oj0z3rUQGvEFlvxEXPdpSw27irFeFNuybkb+ydvQOznryxETZ4F83FkqCQ0pCYlXQ0VI+wUCgSORIZIwEeXY+5r07cB5HwdNm1C6TIk1To53iMLIQNbTNd4wKrv4zLB1b9+YsuPRq5zBHdCReS9CZ5HyfTmFnCdJNlPmeSz6Ha3OGVaYNE6AweNR6vCOIFxCwyuqHnmPv5Dmn5qx74jcywE4KnFWM0mgYjrHcbnXK/83SCspA2GKT4ruUBYS74o/5BtdX++cMqQ1M+QOzfy59TrJlpHwvGDM35b45ZKdP37cd/8tI3f2Pnr6mkAZ2gKtycEAviwlIqQSzuBOK8Z99vRyI3R0FdSF1PwUgIqp9u2/3xDIhkgsy1s74w6XlTOp4ePMaHLg7U7qKObe+Cc3IgzolC10K5oAP3tS78lbLfGAKvGkF6EYCO6GlChEa5xAoyOnUlId3HJuVYDmDaZDGrIiKilC6hdvmuFUPwy3IS0CVkBGg+CHh3Lx317qUrMeeQNMI9lhIg/StwNgGLazH9LK7Kl+dmfpDXA9wDSqs1MfS5Ul1Z5HvNZCrnX6NY7RS8sLUTDVKbUXbZDzis1BzpL1YYKNWS72gy9Xff33P0wdgBudO3695uwKZRJ9IhsfKTrVel/fNDGpfROqaVqXpM+Anp+ZjR6K
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
