---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBTUX3D8xZiTdlcuc1nEuoaAJoyftGVyOdS28+z5Xb6E8hgvneKJsuUPiSjEvtvuRnQG478N0Xwu2D0FUjdrX1sC+mF4UB/GzcpIN42ZS59+J7mvfaDqB1IJ0vISRW3ll1HVQo+j4iYjrmy7S6o8RSzMyFwqH3pErWI28vZnKpjHR91IAR7YfweJxLDDiuxIN/VqRID4wl2i4Cjv10wv89i8lrwUZFD+78cQRkG19TPuRlJbkQthcmptVstE7HWkavQ3sxa29bjfGAP5dn9YLSpSi9jla+018nqqRvateVYx7NWCVgGwbN4nM5C4wVExUdiIpIHsR/c/NAw7IgoYKzdIk8I0lBC+YR10ayFj3872KOuAs9/RFK3sPGjgCOjiCLXWefFBuC8y0EX2vcJiq5hzsO4fJlSro7m6EbkDtFYpe+EEZm5F+ASMhlLeFA8azzVwHdTRcTdpoKW96KfjSDjBp8YmbqLIhNshsAz2yeazYCrHeFR+Eg8VLfD64NNTJ+BduskJV9/4x+amasZpNHKFm5kQix7LxLE2myTYGNYQdRELkpybYQxZ6/guFbDqHlnFbr3HZTF3CkTDI7WU0R74U5IJZO/uJz6EqfXROF6JEO5Rgavf/7giPPZzDwtcux2fO1tOTjDnIdDlsPZrh0bthUoAk219KM4tNkqxlMY5teZ75/7wQdjjy5l2ZOipU1M78rGM1JFTdAWpuaPBKyfob984MXBmzRQ16o+++mdIgpbhGc5mmfu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
