---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAWJykuw5UGADhfJm+bPnCfUWevEiHDvhKwgTjW0x7RPGwReUHDMeB7aDhE06ofgbaMiJ8jsDg6BW4mC9WFYc/dCtQopTJsbbtzO/pwqUAkwC4gOW5GTwNV/ot4i5aZ5ZFWKo9AO2hzOczlrEZf15U9umnUbxcje4pSIC1ykQSCxo4Gfq7J0fC8ejVKaMeTJ/UtPTDQ+oDoXCn3Z5bI6z7EXaYljAFGOAU9kEQ7NA/xn7jgdZb0jL68oYIYjm9DA8pulO9dzd4y+5ZLtq03CRHTNgXf0Qveampmcd4A6VEQH84KUtIZS+EDM4LCHJhP6DcOZ4aNVCr6Q6/7f/O7EjND11crH9SOIcGeVitwBSsVl2iHuyU+7QrdbZlWi8Oygek6jMO/0292Pj4d1/v9epEmZ52tsOwOSqH7aH4TBs4c8DonadXn6GUWBqt85V+A2W+uwkNvcTEDnP0gDJ8oFas3RcIGk5Z7sxeLdCFo9IP8TxgNnCOIjrBVdTvgYplzIQCP4lCFfLcvYmF4I9GSkK8vfPW8uQLx16xanB2dRCat/YbMAEzjsH/ClX2AJ8TcSRIn36FVgxRJt05OKAfrCIXe4yPdvflmMll2BV5nrrgOMojyYDhabkB04f5KE9mR/KsR/J9XSld9YpGsI4E1eJvd43JfMCHKfGUeDZLJk9AKXinOhgtE1wo4yjKAv0xQETY=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
