apiVersion: v1
kind: ConfigMap
metadata:
  name: init-hass-db
  namespace: home-assistant
data:
  init.sh: |
    #!/bin/sh
    set -e
    
    echo "Starting database initialization..."
    
    echo "Testing DNS resolution..."
    nslookup $PGHOST || echo "DNS lookup failed"
    
    echo "Testing PostgreSQL connection..."
    pg_isready -h $PGHOST -U $PGUSER || {
        echo "PostgreSQL not ready, exiting..."
        exit 1
    }
    
    echo "Checking PostgreSQL version..."
    psql -c "SELECT version();"
    
    echo "Checking if homeassistant database exists..."
    DB_EXISTS=$(psql -tAc "SELECT 1 FROM pg_database WHERE datname='homeassistant'")
    
    if [ "$DB_EXISTS" = "1" ]; then
        echo "Database 'homeassistant' already exists"
    else
        echo "Creating homeassistant database..."
        psql -c "CREATE DATABASE homeassistant;"
        echo "Database created successfully"
    fi
    
    echo "Checking if homeassistant user exists..."
    USER_EXISTS=$(psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='homeassistant'")
    
    if [ "$USER_EXISTS" = "1" ]; then
        echo "User 'homeassistant' already exists"
        echo "Updating password for existing user..."
        psql -c "ALTER USER homeassistant WITH PASSWORD '$HASS_PASSWORD';"
    else
        echo "Creating homeassistant user..."
        psql -c "CREATE USER homeassistant WITH PASSWORD '$HASS_PASSWORD';"
        echo "User created successfully"
    fi
    
    echo "Setting database ownership and permissions..."
    psql -c "ALTER DATABASE homeassistant OWNER TO homeassistant;"
    psql -c "GRANT ALL PRIVILEGES ON DATABASE homeassistant TO homeassistant;"
    
    echo "Verifying permissions..."
    psql -c "SELECT datname, datdba::regrole FROM pg_database WHERE datname='homeassistant';"
    
    echo "Database initialization completed successfully!"