apiVersion: batch/v1
kind: Job
metadata:
  name: init-hass-db
  namespace: databases
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: postgres:15-alpine
        command: ["/bin/sh", "/scripts/init.sh"]
        env:
        - name: PGHOST
          value: postgres.databases.svc.cluster.local
        - name: PGDATABASE
          value: postgres
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: postgres-password    # This key matches the encrypted secret
        - name: HASS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-ha-secret
              key: password
              namespace: home-assistant
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: init-hass-db
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4