apiVersion: batch/v1
kind: Job
metadata:
  name: init-hass-db
  namespace: home-assistant
spec:
  template:
    spec:
      serviceAccountName: db-init-sa
      containers:
      - name: init-db
        image: postgres:15-alpine
        command: ["/bin/sh", "/scripts/init.sh"]
        env:
        - name: PGHOST
          value: postgres.databases.svc.cluster.local
        - name: PGDATABASE
          value: postgres
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin-secret
              key: postgres-password
              namespace: databases
        - name: HASS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-ha-secret
              key: password
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: init-hass-db
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-init-sa
  namespace: home-assistant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: databases
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: databases
subjects:
- kind: ServiceAccount
  name: db-init-sa
  namespace: home-assistant
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io